name: API Test CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (or a version compatible with Lombok)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  # Change to 17 or a compatible version

      # Step 3: Cache Maven dependencies (using fresh cache key)
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Compile the project (ensures Lombok annotation processing)
      - name: Compile the project
        run: mvn compile

      # Step 5: Run tests (runs after the code is compiled)
      - name: Run API Tests
        run: mvn test
